;SetCapsLockState "AlwaysOff"
CapsLock::Send "{blind}{Space}"
;Space::Send "{blind}"
Space & j::Send "{blind}{Left}"
Space & k::Send "{blind}{Down}"
Space & l::Send "{blind}{Right}"
Space & i::Send "{blind}{Up}"
Space & h::Send "{blind}{Backspace}"
Space & u::Send "{blind}{Home}"
Space & SC034::Send "{blind}{PgDn}"
Space & o::Send "{blind}{PgUp}"
Space & m::Send "{blind}{End}"
Space & '::Send "{blind}{Insert}"
Space & SC027::Send "{blind}{Del}"
Space & Tab:: Send "{RCtrl Down}z{RCtrl Up}"
